name: Notify Discord on Push

on:
  push:
    paths:
      - 'be-토픽/**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get commit message
      id: get_commit
      run: |
        echo "::set-output name=title::$(git log -1 --pretty=%s)"
        echo "::set-output name=content::$(git log -1 --pretty=%b)"

    - name: Send Discord notification
      uses: wei/curl@v1
      with:
        args: |
          -H "Content-Type: application/json" \
          -d "{\"content\":\"New commit pushed to /be-토픽:\n\n**Title:** ${{ steps.get_commit.outputs.title }}\n**Content:** ${{ steps.get_commit.outputs.content }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_BE }}
