name: Notify Discord on Commit

on:
  push:
    paths:
      - 'be-토픽/**'
      - 'fe-토픽/**'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Determine which directory was changed
        id: determine-directory
        run: |
          if git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -q '^be-토픽/'; then
            echo "directory=be-토픽" >> $GITHUB_ENV
          elif git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -q '^fe-토픽/'; then
            echo "directory=fe-토픽" >> $GITHUB_ENV
          else
            echo "No relevant changes found."
            exit 1

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_BE: ${{ secrets.DISCORD_WEBHOOK_BE }}
          DISCORD_WEBHOOK_FE: ${{ secrets.DISCORD_WEBHOOK_FE }}
          DIRECTORY: ${{ env.directory }}
        run: |
          if [ "$DIRECTORY" = "be-토픽" ]; then
            WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_BE }}
          elif [ "$DIRECTORY" = "fe-토픽" ]; then
            WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_FE }}
          else
            echo "Unknown directory."
            exit 1
          fi

          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          COMMIT_URL=${{ github.event.head_commit.url }}
          AUTHOR_NAME=${{ github.event.head_commit.author.name }}
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"**New Commit**\nAuthor: $AUTHOR_NAME\nMessage: $COMMIT_MESSAGE\n[View Commit]($COMMIT_URL)\"}" \
               $WEBHOOK_URL
