name: Notify Discord on Commit

on:
  push:
    paths:
      - 'be-토픽/**'

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get last commit message
      id: get_commit
      run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s%n%b')"

    - name: Send message to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_BE }}
      run: |
        COMMIT_MESSAGE="${{ steps.get_commit.outputs.message }}"
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"New commit in the repository:\n${COMMIT_MESSAGE}\"}" \
             $DISCORD_WEBHOOK_URL
